;--------------------------------------------------------------------------------------
; 장비 운용 모션 파라미터 설정
; 
;--------------------------------------------------------------------------------------
[AXIS_X]
ScaleUnit =10000.000
ScaleUnit_desc = X축 스케일 단위 값

GcodeOffset =0.000
GcodeOffset_desc = Gcode 원점 기준 offset 값

HomeOffset =0.000
HomeOffset_desc = HomeOffset 값
Limit_Min =-101.000
Limit_Min_desc = Negative Limit
Limit_Max =101.000
Limit_Max_desc = Positive Limit
Interlock_Min =-100.000
Interlock_Min_desc = Negative Interlock
Interlock_Max =100.000
Interlock_Max_desc = Positive Interlock
Limit_Used =0
Limit_Used_desc = Interlock 사용 유무

Default_REL_Val =0.100
Default_REL_Val_desc = REL 모드 이동값

Default_ABS_Val =1.000
Default_ABS_Val_desc = ABS 모드 이동값

Fast_Speed =20000.000
Fast_Speed_desc = 빠른 속도

Fast_Acc =200.000
Fast_Acc_desc = 빠른 가감속

Normal_Speed =5000.000
Normal_Speed_desc = 일반 속도

Normal_Acc =200.000
Normal_Acc_desc = 일반 가감속

Slow_Speed =100.000
Slow_Speed_desc = 느린 속도

Slow_Acc =200.000
Slow_Acc_desc = 느린 가감속

[AXIS_Y]
ScaleUnit=10000.000
ScaleUnit_desc=X축 스케일 단위 값

GcodeOffset=0.000
GcodeOffset_desc=Gcode 원점 기준 offset 값

HomeOffset =0.000
HomeOffset_desc = HomeOffset 값
Limit_Min =-101.000
Limit_Min_desc = Negative Limit
Limit_Max =101.000
Limit_Max_desc = Positive Limit
Interlock_Min =100.000
Interlock_Min_desc = Negative Interlock
Interlock_Max =100.000
Interlock_Max_desc = Positive Interlock
Limit_Used =0
Limit_Used_desc = Interlock 사용 유무

Default_REL_Val =0.100
Default_REL_Val_desc = REL 모드 이동값

Default_ABS_Val =1.000
Default_ABS_Val_desc = ABS 모드 이동값

Fast_Speed =20000.000
Fast_Speed_desc = 빠른 속도

Fast_Acc =200.000
Fast_Acc_desc = 빠른 가감속

Normal_Speed =5000.000
Normal_Speed_desc = 일반 속도

Normal_Acc =200.000
Normal_Acc_desc = 일반 가감속

Slow_Speed =100.000
Slow_Speed_desc = 느린 속도

Slow_Acc =200.000
Slow_Acc_desc = 느린 가감속

[AXIS_Z]
ScaleUnit=10000.000
ScaleUnit_desc=X축 스케일 단위 값

GcodeOffset=0.000
GcodeOffset_desc=Gcode 원점 기준 offset 값

HomeOffset =0.000
HomeOffset_desc = HomeOffset 값
Limit_Min =-2.831
Limit_Min_desc = Negative Limit
Limit_Max =123.511
Limit_Max_desc = Positive Limit
Interlock_Min =-120.000
Interlock_Min_desc = Negative Interlock
Interlock_Max =110.000
Interlock_Max_desc = Positive Interlock
Limit_Used =1
Limit_Used_desc = Interlock 사용 유무

Default_REL_Val =0.100
Default_REL_Val_desc = REL 모드 이동값

Default_ABS_Val =1.000
Default_ABS_Val_desc = ABS 모드 이동값

Fast_Speed =5000.000
Fast_Speed_desc = 빠른 속도

Fast_Acc =200.000
Fast_Acc_desc = 빠른 가감속

Normal_Speed =100.000
Normal_Speed_desc = 일반 속도

Normal_Acc =200.000
Normal_Acc_desc = 일반 가감속

Slow_Speed =5.000
Slow_Speed_desc = 느린 속도

Slow_Acc =200.000
Slow_Acc_desc = 느린 가감속
