[MOTOR]
IP=192.168.0.200
; 1 = Homing , 10 = ing , 100 = Done 
; 2 = Cancel , 200 = Cancel Done 
ALL_HOME=All_Homing

; 1 = All Stop , 100 = All Stop Done
ALL_STOP=AllStop

[COMMON_CMD]
GCODE_RUN = Gcode_Run
GCODE_LINE_NO = GLN
IN_EMG_STOP		= In_EMGStop
PREPARATION_MOVE = FeedrateRapidMove
WORK_MOVE = FeedrateGcode
AC_ROTATION_SPEED = FeedrateACAxis
LASER_SHUTTER = LaserShutter
LASER_CTRL_SELECTOR = LaserCtrlSelector
TTL_OUTPUT_TIME = TTLOutputTime
LaserCtrlSelector = LaserCtrlSelector
TTLOutputTime = TTLOutputTime

[X]
SERVO=Mtr1_ServoOnOff
HOME=Mtr1_Homing 
ALARM_RESET=Mtr1_AlarmReset
MOVE_MODE=Mtr1_MoveCmd
TARGET_POS=Mtr1_TargetPos
MOVE_SPEED=Mtr1_MoveSpd
MOVE_ACC_DEC=Mtr1_MoveAccTime
JOG_MODE=Mtr1_JogCmd
JOG_SPEED=Mtr1_JogSpeed
JOG_ACC_DEC=Mtr1_JogAccTime
NOW_POS=Mtr1_Pos
STATUS=Mtr1_Status

[Y]
SERVO=Mtr2_ServoOnOff
HOME=Mtr2_Homing 
ALARM_RESET=Mtr2_AlarmReset
MOVE_MODE=Mtr2_MoveCmd
TARGET_POS=Mtr2_TargetPos
MOVE_SPEED=Mtr2_MoveSpd
MOVE_ACC_DEC=Mtr2_MoveAccTime
JOG_MODE=Mtr2_JogCmd
JOG_SPEED=Mtr2_JogSpeed
JOG_ACC_DEC=Mtr2_JogAccTime
NOW_POS=Mtr2_Pos
STATUS=Mtr2_Status

[Z]
SERVO=Mtr3_ServoOnOff
HOME=Mtr3_Homing 
ALARM_RESET=Mtr3_AlarmReset
MOVE_MODE=Mtr3_MoveCmd
TARGET_POS=Mtr3_TargetPos
MOVE_SPEED=Mtr3_MoveSpd
MOVE_ACC_DEC=Mtr3_MoveAccTime
JOG_MODE=Mtr3_JogCmd
JOG_SPEED=Mtr3_JogSpeed
JOG_ACC_DEC=Mtr3_JogAccTime
NOW_POS=Mtr3_Pos
STATUS=Mtr3_Status

[MIRROR]
SERVO=MtrMirror_OnOff

[LENS]
SERVO=MtrObject_OnOff
