;--------------------------------------------------------------------------------------
; 비트버스 조명 제어
;--------------------------------------------------------------------------------------
[CONNECT]
COM=11
BAUDRATE=38400

[SCANNER]
CH1=0
CH2=0
CH3=0
CH4=0
CH5=0
