;--------------------------------------------------------------------------------------
; ZeroG 보드제어
;--------------------------------------------------------------------------------------
[CONNECT]
COM=5
